### PR TITLE
Bump to C++SDK 2.4.2

### PR DESCRIPTION
**Pull request by djova-dolby**
- Fixed issue where fail to join conference if the conference was created without rtcp_mode specified
- Audio levels event now returns local participant audio level even if muted

### CODE REVIEW

**Review by Adam1-3 — APPROVED** [review]

**Review by FabienLavocat — DISMISSED** [review]

**Comment by djova-dolby** [comment]
@FabienLavocat I bumped to 2.4.2 as this fixes possible crash in webrtc stats parsing. Considering this has been open for a while and moving from 2.4.0 -> 2.4.2 prevents some possible issues I think we should merge it.

**Review by FabienLavocat — APPROVED** [review]

**Comment by kubaau** [comment]
@Adam1-3 @djova-dolby This should have been merged to develop first and also every time we change the SDK we should align the "build from source" docs, or somehow change these docs to not need to do so.

**Comment by djova-dolby** [comment]
Ok makes sense, my bad honestly and totally understood. As I said on slack I do not know the protocol's for unreal project develop/main/releasing and hence this is why I did not want to merge anything myself. But now I know for future reference.
I thought it good to update to the new sdk packages to hopefully preemptively prevent hitting the bugs outlined in commits which were found in 2.4 release.

**Comment by kubaau** [comment]
No worries, the flow is kind of artificial at this point anyway.

**Pull request merged**
