### PR TITLE
Extend Blueprint sample: add debug information, automated test

### PR DESCRIPTION
**Pull request by kubaau**
Added local participant, remote participant, active speaker and audio level information.

Also changed position and rotation to not be modifiable from the editor as it is fairly useless.

### CODE REVIEW

**Comment by kubaau** [comment]
Since most of the changes are in Blueprints I'll explain here what has been done:

This entire section is new:
bdi1

Here I extended reacting after disconnecting:
bdi2

I also placed a timer to periodically query for audio levels:
bdi3

And this is what it looks like:
bdi4

**Comment by Adam1-3** [comment]
Let's reduce BPs and as we discussed:  remove debug info widget.

**Comment by kubaau** [comment]
> Let's reduce BPs and as we discussed: remove debug info widget.

I thought about this some more and I think it may be useful to keep it since the editor details which, as we've spoken, already show this information, are not available in a packaged game. I would not like to remove it just now, I would at least like to think about this some more and I don't have time to work on this right now anyway.

**Comment by kubaau** [comment]
Initial version of the automated smoke test:

bdi5

It's a bit of a mess but it can be useful for testing, at least until we automate this some more (but I cannot work on this right now).

**Comment by Adam1-3** [comment]
> Initial version of the automated smoke test:
> 
> bdi5
> 
> It's a bit of a mess but it can be useful for testing, at least until we automate this some more (but I cannot work on this right now).

It's a good example of expressing logic in UE blocks, but it also shows that it is way better to express it in C++ (and we could track its history of changes in repo).

**Review by jfan-dolby — APPROVED** [review]

**Comment by kubaau** [comment]
Outdated - closing.

**Pull request closed without merging**
