### PR TITLE
Fix deadlock when closing game while screensharing an Unreal Editor window on Windows

### PR DESCRIPTION
**Pull request by kubaau**

### CODE REVIEW

**Comment by kubaau** [comment]
@djova-dolby This may be a sign of an issue within the SDK. This is just a hack. If I use Unreal Editor, launch the game, share the Unreal Editor window and close the game, the SDK gets stuck in the destructor waiting endlessly on `fut.get();`. It never reaches either `.then([this, prom]() {` or `.on_error([this, prom](std::exception_ptr&&) {` just above because
```
 return iapi::async_destructible_deleter<
                iapi::media_device_manager>::destroy(std::move(media_manager_));
```
never returns. I can give you a minidump or we can debug this together somehow.

**Review by djova-dolby — APPROVED** [review]

**Comment by djova-dolby** [comment]
> 

On desktop's it doesn't deadlock when you close the window that is being shared, but in that case the window is not also the one running the application using the SDK. If I share terminal window that is running showcase app and then shut it down, it does exit but it could be that terminal does some force destruction on the app running inside. Who knows. 
Giving me logs with media set to INFO maybe can help, then I can see what the desktop capture thread is doing. I am not sold on the issue being solely SDK specific, because if it was I think shutting down the SDK while doing any screen share would produce the issue right? I could be wrong though.
In 2.5 we do have the known issue where we don't provide information to applications that the window they have being sharing has been stopped. Maybe adding this will alleviate the issue.
It has to be hanging in the shutting down of the media-engine, I would assume when clearing the video tracks from the map, which in turn shuts down the video pipelines and kills the capturers. Not sure if you have it connected to a debugger or if you can add some logs to the SDK to see how far in the destructor it gets but maybe this will help us spot exactly where the problem is.

**Comment by djova-dolby** [comment]
So I can detect that window has disappeared:
```
[08:22:59.233373] error   [webrtc] (window_capturer_mac.mm:155): The window is not valid any longer.
[08:22:59.233411]  error   [webrtc] (desktop_capturer.cc:213): Permanent error in Desktop Capture!
```
I can propagate this outward as a screen_share_error event or something, which will fix our known issue. But still not sure if this will fix the Unreal deadlock.

**Comment by kubaau** [comment]
I am also not sure where the problem lies exactly, but we can debug this together. I will send you a minidump and cppsdk logs and if you can't find anything I can screenshare my editor to show you. Or you I can show you how to set up the plugin yourself if you can install UE (4.27 is lighter and also reproduces the issue) on your VM.

**Pull request merged**
