### PR TITLE
Updated On Video Track Added/Remove pages.

### PR DESCRIPTION
**Pull request by adamallaf**
Updated On Video Track Added/Remove pages.

### CODE REVIEW

**Comment by adamallaf** [comment]
I'm unable to sign the CLA, clicking the sign button results in a 504 error.

**Review by kubaau — DISMISSED** [review]

**Comment by kubaau** [comment]
@FabienLavocat @jfan-dolby Can you advise @adamallaf on his issue?

**Comment by FabienLavocat** [comment]
> @FabienLavocat @jfan-dolby Can you advise @adamallaf on his issue?

We are working on a fix.

**Comment by FabienLavocat** [comment]
> I'm unable to sign the CLA, clicking the sign button results in a 504 error.

@adamallaf could you please give it a new try, we deployed a fix.

**Comment by adamallaf** [comment]
Thanks @FabienLavocat, signing CLA works.

**Review by kubaau — APPROVED** [review]

**Pull request merged**
